kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.k8s.johnchen.dev
    tls:
      - secretName: wildcard-tls-secret
        hosts:
          - grafana.k8s.johnchen.dev
    envFromSecret: grafana-oidc
    grafana.ini:
      server:
        root_url: https://grafana.k8s.johnchen.dev
      auth.generic_oauth:
        enabled: true
        name: Pocket ID
        allow_sign_up: true
        # client_id and client_secret come from envFromSecret above
        scopes: openid email profile
        auth_url: http://pocket-id.k8s.johnchen.dev/authorize
        token_url: http://pocket-id.k8s.johnchen.dev/api/oidc/token
        api_url: http://pocket-id.k8s.johnchen.dev/api/oidc/userinfo
        use_pkce: true
