apiVersion: v2
name: nvidia
description: Self hosted nvidia device plugin
version: 1.0.0
type: application
dependencies:
  - name: nvidia-device-plugin
    version: 0.18.0
    repository: https://nvidia.github.io/k8s-device-plugin
