apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-talos.yaml
    path: apps/nvidia
    repoURL: https://github.com/kryptonite303/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
