apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: homelab
  chart: ./charts/metallb
  valuesFiles:
    - ./charts/metallb/values-talos.yaml
  ignoreMissingValuesFiles: true
