apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: nginx
  path: "./deployments/common"
  prune: true
  timeout: 1m
