apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  storage:
    size: 10Gi
    storageClass: iscsi
  superuserSecret:
    name: superuser-secret
  enableSuperuserAccess: true
  managed:
    roles:
      - name: paperless
        login: true
        password:
          type: Password
          value: paperless
