apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: paperless
  data:
  - secretKey: PAPERLESS_SOCIALACCOUNT_PROVIDERS
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /paperless/PAPERLESS_SOCIALACCOUNT_PROVIDERS
      metadataPolicy: None
