apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume
  namespace: paperless
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb
  volumeMode: Filesystem
  volumeName: pvc-fd909158-69ef-4ee2-998a-d374fc24d510
