apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/nginxinc/kubernetes-ingress
  ref:
    branch: main
