apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ssh-key
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: ssh-key
  data:
  - secretKey: ssh-key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /cert-sync/ssh-key
      metadataPolicy: None
