apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  storage:
    size: 50Gi
    storageClass: iscsi
  superuserSecret:
    name: superuser-secret
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - vectorchord
  managed:
    roles:
      - name: immich
        connectionLimit: -1
        inherit: true
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: superuser-secret
