apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18
  storage:
    size: 50Gi
    storageClass: iscsi
  superuserSecret:
    name: superuser-secret
  enableSuperuserAccess: true
  postgresql:
    enableAlterSystem: true
    shared_preload_libraries:
      - "vchord.so"
