apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: cert-manager
spec:
  secretName: wildcard-tls-secret
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  secretTemplate:
    annotations:
{{- with .Values.certificate.annotations }}
{{ toYaml . | indent 6 }}
{{- end }}
