apiVersion: v2
name: cert-manager
description: Self hosted cert-manager
version: 1.0.0
type: application
dependencies:
  - name: cert-manager
    version: 1.19.1
    repository: https://charts.jetstack.io
