apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: grafana-oidc
  data:
  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /grafana/GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      metadataPolicy: None
  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /grafana/GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      metadataPolicy: None
